server:
  port: 9090

spring:
  application:
    name: panel-api

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    properties:
      schema.registry.url: "http://localhost:8081"
      auto.register.schemas: true
    streams:
      properties:
        schema.registry.url: "http://localhost:8081"
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        schema.registry.url: "http://localhost:8081"

    admin:
      properties:
        schema.registry.url: "http://localhost:8081"
    consumer:
      properties:
        schema.registry.url: "http://localhost:8081"