server:
  port: 9090

spring:
  application:
    name: panel-api

  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USER}
    password: ${DATA_SOURCE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}

    admin:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}

