version: '3.7'

services:

  elasticsearch:
    image: elastic/elasticsearch:8.3.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_USERNAME: test
      ELASTIC_PASSWORD: test
      discovery.type: single-node
      xpack.security.enabled: "false"
    networks:
      - elk

  kibana:
    image: elastic/kibana:8.3.3
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: test
      ENABLED_SECURITY: "false"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge